apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      type: {{ .Values.labels.type }}
  template:
    metadata:
      labels:
        type: {{ .Values.labels.type }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livelinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livelinessProbe.periodSeconds }}
            successThreshold: {{ .Values.livelinessProbe.successThreshold }}
            failureThreshold: {{ .Values.livelinessProbe.failureThreshold }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: ms-sophie
                  key: API_KEY
            - name: SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: ms-sophie
                  key: SERVICE_NAME
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ms-sophie
                  key: OTEL_EXPORTER_OTLP_ENDPOINT