image:
  repository: marcosls/sophie-api
  tag: v1
  pullPolicy: IfNotPresent
namespace: ms-sophie
replicaCount: 2
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
labels:
  type: ms
livelinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
service:
  type: NodePort 
  port: 80
  targetPort: 8000
  nodePort: 30000
canary:
  enabled: true
  duration: 60
  weightSteps: [10, 50, 100]
